export const USER_REQUESTED = "USER_REQUESTED";
export const USER_REQUEST_SUCCESS = "USER_REQUEST_SUCCESS";
export const USER_REQUEST_PENDING = "USER_REQUEST_PENDING";
export const USER_REQUEST_FAILED = "USER_REQUEST_FAILED";
export const USER_SUBMITTED = "USER_SUBMITTED";
export const USER_SUBMIT_SUCCESS = "USER_SUBMIT_SUCCESS";
export const USER_SUBMIT_FAILED = "USER_SUBMIT_FAILED";
export const USER_SUBMIT_PENDING = "USER_SUBMIT_PENDING";
export const USER_MODEL_CHANGE = "USER_MODEL_CHANGE";



